// Ad slots shown to ALL visitors.
// Generated by Admin > Ad Manager > "Export ads-config.js". Upload the exported file to the js/ folder on your hosting (replace this one).
window.SITE_AD_CONFIG = { globalAdsEnabled: true, slots: [] };
